### ISSUE TITLE
v0.99.5 and 256^3 multi model support

### ISSUE THREAD

**Issue by unphased** [aiekick/MagicaVoxel_File_Writer#3]
Hey there @aiekick, 

I noticed that the latest MagicaVoxel windows release 0.99.5 supports 256^3 model sizes and also fails to load the format that this code produces. I made a trivial modification to the code that shows that it can export 256^3 blocks (and the first of which loads) but the multi block loading functionality appears to be changed and no longer works. 

Since you were able to reverse engineer the format, I was wondering if you could take a stab at it again. :smile:

**Comment by aiekick** [comment]
sorry but i have no time for that at this moment.
i have not reverse enginner the format, because i used this file : https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt

**Comment by unphased** [comment]
Nice! I'll do some more experiments. It looks like your fixes that I have not pulled into my fork branch allow this to work. I will check with you if I get really stuck with it. Thanks!
