### ISSUE TITLE
Support for converting pointclouds with decimal coordinates

### ISSUE THREAD

**Issue by gongarher** [aiekick/MagicaVoxel_File_Writer#4]
Hi! I have been voxelizing some maps with your awesome software, but I'm facing some resolution issues due to my points coordinates are not integers and I'm working with decimal part too (0.25 meter resolution). I have tried to modify your lib but I don't know where to start as most functions are based on int32 arguments. It would be great to add support for float coordinates.

As my resolution is 0.25, I have tried multiplying all coordinates by four and it results in a rare tower (which has nothing to do with the real map) maybe it's because points go out of MagicaVoxel's range. Proof:

![image](https://user-images.githubusercontent.com/75259141/136356912-e400f68d-e17a-40ad-a392-ab75283ba568.png)
![image](https://user-images.githubusercontent.com/75259141/136356966-7d4731c0-fc72-4918-9a4d-84c9ec35335d.png)

My point cloud file looks like this example:

> 7228
511.0 291.5 27.75
511.0 291.75 27.75
510.75 292.0 27.75
510.75 291.25 28.0
510.75 291.5 28.0
510.75 291.75 28.0
511.75 291.0 28.0
511.0 291.5 28.0
509.75 292.5 28.0
510.5 292.25 28.0
510.75 292.25 28.0
510.75 292.5 28.0
511.0 292.0 28.0
511.0 292.25 28.0
503.75 303.5 30.0
506.75 297.75 26.5
507.25 297.5 26.5
507.0 297.75 26.5
507.25 297.75 26.5
506.75 297.5 27.0
506.75 297.75 27.0
506.75 297.75 27.25
506.75 297.25 27.5
506.75 297.25 27.75
506.75 297.5 27.5
506.5 297.75 27.5
506.75 297.75 27.5
506.75 297.5 27.75
506.75 297.75 27.75
507.0 297.5 27.0
507.0 297.5 27.25
507.0 297.75 27.25
507.0 297.75 27.75

**Comment by aiekick** [comment]
ok seems good. can you give me a pcd file and the expected result ?

(you can use a array for map_color instead of a list of check)

**Comment by gongarher** [comment]
Sure!
Expected result visualized on rviz, each cube is 0.25 meters. I'm looking for the same result when voxelizing my pointcloud. This picture is a part of the whole map.
![a](https://user-images.githubusercontent.com/75259141/136376608-dfe6377d-3145-4261-9484-fafe00f511f4.png)

MagicaVoxel result. Here you can see the loss of resolution.
![image](https://user-images.githubusercontent.com/75259141/136376792-d41db283-8b7c-4130-a6f8-0fc396ecaf82.png)


To clarify, this picture shows the pointcloud that is stored in the attached file but points are visualized on rviz as 0.25 meters cubes:
![b](https://user-images.githubusercontent.com/75259141/136377009-3048f6e0-bc55-4aab-8543-c43218c52e6a.png)

PCD file: 
[resolution-issue.zip](https://github.com/aiekick/MagicaVoxel_File_Writer/files/7302758/resolution-issue.zip)

This file is a cropped part of the global map, its points correspond to the cubes shown in the last picture.
Thanks for your time and effort! :)

**Comment by aiekick** [comment]
dont know, maybe you can recenter your model. but for that you need to calc the min max range of each voxel first.

maybe can be an option in the lib after all points adding
